version: '3'

services:

  app-ganado:
    build:
      context: ./
      dockerfile: dockerfile.prod
      args:
        - VACAS_DATABASE_URL=${VACAS_DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${VACAS_DATABASE_URL}